os: linux
dist: xenial
language: node_js
branches:
  only:
    - master
cache:
  yarn: true
script:
  - npm run test --verbose
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
before_deploy:
  - yarn build
# deploy:
#   provider: script
#   script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir ./build
#   skip_cleanup: true
#   on:
#     branch: master
