language: node_js
node_js:
  - '12.13.1'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
  - NODE_ENV=production
  - BABEL_ENV=production

install:
  - npm install
# script:
#   - yarn test --collect-coverage --verbose

# after_success:
#   - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

# before_deploy:
#   - yarn build

# deploy:
#   provider: script
#   script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir ./build
#   skip_cleanup: true
#   on:
#     branch: master
